### ISSUE TITLE
Stale model object in mapbayr causing reverse dependency issues

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#1299]
@FelicienLL @kyleam 

```r
Package check result: OK

Changes to worse in reverse depends:

Package: mapbayr
Check: tests
New result: ERROR
    Running ‘testthat.R’ [38s/39s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(mapbayr)
    
    Attaching package: 'mapbayr'
    
    The following object is masked from 'package:stats':
    
        filter
    
    > 
    > test_check("mapbayr")
    Building pchelle_mod ... done.
    Building mod_getparam ... done.
    Building mod12 ... done.
    
    [==============================================================] ID 4/4 (100%)
                                                                                  
    Attaching package: 'mrgsolve'
    
    The following object is masked from 'package:stats':
    
        filter
    
    
    
    [ FAIL 3 | WARN 37 | SKIP 4 | PASS 711 ]
    
    ══ Skipped tests (4) ═══════════════════════════════════════════════════════════
    • On CRAN (4): 'test-progress.R:5:3', 'test-reset-conditions.R:3:3',
      'test-reset-conditions.R:93:3', 'test-reset-conditions.R:175:3'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-hist.R:42:3'): SHK is shown if n ID > 1 ────────────────────────
    Error in `eval(substitute(expr), e)`: no slot of name "itol" for this object of class "mrgmod"
    Backtrace:
         ▆
      1. ├─graphics::hist(est001) at test-hist.R:42:3
      2. └─mapbayr:::hist.mapbayests(est001)
      3.   ├─base::data.frame(...)
      4.   └─mapbayr:::eta_descr(x$model)
      5.     ├─base::as.list(x)
      6.     └─mrgsolve::as.list(x)
      7.       └─mrgsolve (local) .local(x, ...)
      8.         ├─base::within(...)
      9.         └─base::within.list(...)
     10.           └─base::eval(substitute(expr), e)
     11.             └─base::eval(substitute(expr), e)
    ── Error ('test-hist.R:70:3'): ID percentile is not shown if n ID > 1 ──────────
    Error in `eval(substitute(expr), e)`: no slot of name "itol" for this object of class "mrgmod"
    Backtrace:
         ▆
      1. ├─graphics::hist(est001) at test-hist.R:70:3
      2. └─mapbayr:::hist.mapbayests(est001)
      3.   ├─base::data.frame(...)
      4.   └─mapbayr:::eta_descr(x$model)
      5.     ├─base::as.list(x)
      6.     └─mrgsolve::as.list(x)
      7.       └─mrgsolve (local) .local(x, ...)
      8.         ├─base::within(...)
      9.         └─base::within.list(...)
     10.           └─base::eval(substitute(expr), e)
     11.             └─base::eval(substitute(expr), e)
    ── Error ('test-use_posterior.R:73:3'): multi ID ───────────────────────────────
    Error in `eval(substitute(expr), e)`: no slot of name "itol" for this object of class "mrgmod"
    Backtrace:
         ▆
      1. ├─est001 %>% use_posterior(update_omega = TRUE) at test-use_posterior.R:73:3
      2. └─mapbayr::use_posterior(., update_omega = TRUE)
      3.   └─mapbayr:::mbr_cov_names(mod)
      4.     ├─base::as.list(x)
      5.     └─mrgsolve::as.list(x)
      6.       └─mrgsolve (local) .local(x, ...)
      7.         ├─base::within(...)
      8.         └─base::within.list(...)
      9.           └─base::eval(substitute(expr), e)
     10.             └─base::eval(substitute(expr), e)
    
    [ FAIL 3 | WARN 37 | SKIP 4 | PASS 711 ]
    Error: Test failures
    Execution halted
```

**Comment by kyleam** [comment]
All of these errors involve `data/est001.rda`.  I suspect that needs to be regenerated (by running `data-raw/est001.R` with the latest mrgsolve) so that the underlying mrgsolve object has the slot.

**Comment by kyleam** [comment]
As a side remark: when running the mapbayr test suite, I noticed that there were 37 warnings, and, at a glance, they all seem to be something like this:

```
Warning ('test-pcvpc.R:70:3'): vpc_sim() works
The following argument was passed to `mrgsolve::update()`, but
it is either an invalid name (check your spelling?) or not an
eligible attribute for update:
x ORIGID
Backtrace:
     ▆
  1. ├─mapbayr:::vpc_sim(mod, data3, nrep = 10, end = 24) at test-pcvpc.R:70:3
  2. │ ├─... %>% pivot_sims() at mapbayr/R/pcvpc.R:147:5
  3. │ ├─dplyr::bind_rows(...) at tidyr/R/pivot-long.R:153:3
  4. │ │ └─rlang::list2(...) at dplyr/R/bind-rows.R:31:3
  5. │ └─purrr::pmap(...) at rlang/R/dots.R:91:3
  6. │   └─purrr:::pmap_("list", .l, .f, ..., .progress = .progress) at purrr/R/pmap.R:101:3
  7. │     ├─purrr:::with_indexed_errors(...) at purrr/R/pmap.R:166:3
  8. │     │ └─base::withCallingHandlers(...) at purrr/R/map.R:268:3
  9. │     ├─purrr:::call_with_cleanup(...) at purrr/R/pmap.R:166:3
 10. │     └─mapbayr (local) .f(...)
 11. │       └─mrgsolve::mrgsim(...) at mapbayr/R/sim.R:126:3
 12. │         └─mrgsolve::mrgsim_d(x, data = data, ...)
 13. │           ├─base::do.call(...)
 14. │           └─mrgsolve (local) `<fn>`(...)
 15. │             ├─stats::update(x, ..., strict = TRUE)
 16. │             └─mrgsolve::update(x, ..., strict = TRUE)
 17. │               └─mrgsolve (local) .local(object, ...)
 18. └─mapbayr:::pivot_sims(.) at magrittr/R/pipe.R:136:3
 19.   └─tidyr::pivot_longer(...) at mapbayr/R/augment.R:155:3
──────────────────────────────────────────────────────────────────
```

The same 37 warnings happen with mrgsolve 1.5.3, so those warnings appear to be unrelated to the new release.

**Comment by FelicienLL** [comment]
> That looks unrelated to the mrgsolve update. When mapbayr's [1d0f748](https://github.com/FelicienLL/mapbayr/commit/1d0f7480b31df803cac17746aded10c6e42cc7f7) (lambda in ofv ..., 2023-01-30) introduced `lambda`, I think it should have regenerated the rda and updated the slot assertion in test-output.R to include `lambda`.
> 
> https://github.com/FelicienLL/mapbayr/blob/3ae0c7204737427b3cae9e2919dafd9b1b0ff8da/tests/testthat/test-output.R#L4
> 
> In other words the test assertion only passes because it's against a stale rda.

Thanks a lot for catching this one... It should be fixed now.


> As a side remark: when running the mapbayr test suite, I noticed that there were 37 warnings, and, at a glance, they all seem to be something like this:
> 
> ```
> Warning ('test-pcvpc.R:70:3'): vpc_sim() works
> The following argument was passed to `mrgsolve::update()`, but
> it is either an invalid name (check your spelling?) or not an
> eligible attribute for update:
> x ORIGID
> The same 37 warnings happen with mrgsolve 1.5.3, so those warnings appear to be unrelated to the new release.

Indeed, I can see that it seem to be the case since 1.1.0 after the introduction of mrgsolve::update() warning in case of invalid names... Now fixed.

**Comment by kylebaron** [comment]
Hi @FelicienLL  - 

I'm still getting caught up on correspondence since being out of office at the University today. But thanks for the PR; I can take a look and test with the version that we want to submit to CRAN. There were three additional slots in the model object; so I think if you make the object with 1.6.1 and freeze, when it gets picked up by an earlier version (like 1.5.2) mrgsolve will just ignore those slots when creating the list output. So as I understand it, this makes sense to me. I'll have to start some revdevcheck process before releasing, at least whenever there's a change to the object to pick this up before hand. Anyway, thanks for your time on a Friday evening to do this and I'll get a report back to you this weekend to see what I find. 

Kyle

**Comment by kylebaron** [comment]
Thanks for testing that, @kyleam ; it would have taken me a couple of hours to get everything set up and I'd trust your assessment before I'd trust mine. 

I'll chime in if I can think of anything this weekend, but IMO this sounds good to go @FelicienLL

**Comment by FelicienLL** [comment]
Hi both, mapbayr 0.10.1 is now on CRAN. 
Best regards
Félicien

**Comment by kyleam** [comment]
@kylebaron I think everything's settled here, but please reopen if I'm mistaken.
